### ISSUE TITLE
[Meta] Memory and runtime performance improvements

### ISSUE THREAD

**Issue by standage** [dib-lab/kevlar#272]
Here I want to keep track of some ideas we've thought of and, in some cases, discussed to improve kevlar's memory consumption and speed. I'll link to relevant issue threads and pull requests as they come about.

- [ ] Buffer abundance queries in `kevlar novel` (see #208)
- [ ] Use a faster hash function (see #209)
- [ ] Re-visit and re-evaluate error correction
- [ ] Populate dedicated counttables for the `kevlar simlike` step, to enable higher FPR for `kevlar novel` step
- [ ] Investigate sketch composition so controls can be combined for `kevlar novel` step

**Comment by standage** [comment]
It turns out that applying the mask at k-mer counting time (`kevlar count`) has all kinds of downstream efficiency benefits. See #277.
